# une valeur similaire par ligne donc on peut supprimer REG13C car c'est des colonnes identiques
# colonnes vides et constantes à supp  : vides : ['Q2_r10', 'Q2_r11']
# /!\ plusieurs colonnes contiennent la localisation 
# data lakaege REG(9zones UDA), REG2(5 zones), REG3, REG13C, AGGLOIFOP2(nb habitants mais un peu lié au lieu de vie)
# on garde REG13 & 3 en gros REG3 c'est soit ile de france soit province et REG13 c'est les region en entier

In [6]:
pip install odfpy

Defaulting to user installation because normal site-packages is not writeable
Collecting odfpy
  Downloading odfpy-1.4.1.tar.gz (717 kB)
     ---------------------------------------- 0.0/717.0 kB ? eta -:--:--
     ------------------------------------- 717.0/717.0 kB 17.1 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: defusedxml in c:\users\eleon\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from odfpy) (0.7.1)
Building wheels for collected packages: odfpy
  Building wheel for odfpy (pyproject.toml): started
  Building wheel for odfpy (pyproject.toml): finished with status 'done'
  Created wheel for odfpy: filename=odfpy-1.4.1-py2.py3-none-any.whl size=137565 sha256=7c28d93f5880011b3fcf702d493c8192be3dcde9d47ff7b779d3f0dc09aa3c0e
  Stored in directory: c:\users\eleon\appdata\local\pip\cache\wheels\8e\cd\9f\979443982946991080916064e4c049b91941be1800825ff74b
Successfully built odfpy
Installing collected packages: odfpy
Successfully installed odfpy-1.4.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0 -> 26.2.1
[notice] To update, run: C:\Users\eleon\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [22]:
import pandas as pd
import numpy as np

In [23]:
path = "../documentation/hadopi-2020-musique-data.ods"

df = pd.read_excel(path, engine="odf")
df = df.replace('#NUL!', np.nan)

C:\Users\eleon\AppData\Local\Temp\ipykernel_22596\3576167298.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace('#NUL!', np.nan)

In [24]:
df.head()

,SEXE,QSEXE,RAGE2,RAGE3,XRAGE,AGGLOIFOP2,REG,REG2,REG3,REG13,...,Q60_3,Q60_4,Q60_5,Q61_r1_c1,Q61_r2_c1,Q61_r3_c1,Q61_r4_c1,DISPQUAL,sys_block_set_1,poids
0,Une femme,FEMME,De65aPlus,PlusDe49ans,Femme35ansEtPlus,MoinsDe100000Habitants,UDA7,BUDA4,PROVINCE,LanguedicRoussillonMidiP,...,NaN,NaN,NaN,NaN,Entre 1 et 49,NaN,NaN,Long,"2,3,1",1.006791
1,Une femme,FEMME,De50a64ans1,PlusDe49ans,Femme35ansEtPlus,PlusDe100000Habitants,UDA6,BUDA3,PROVINCE,PaysDeLaLoire1,...,0,0,0,150 et plus,50 et plus,NaN,NaN,Long,"3,2,1",0.695394
2,Une femme,FEMME,De15a24ans,MoinsDe35ans,FemmeMoinsDe35ans,PlusDe100000Habitants,UDA2,BUDA2,PROVINCE,NordPasDeCalaisPicardie,...,L’offre légale est plus agréable à utiliser,0,0,Entre 50 et 99,NaN,Entre 50 et 99,NaN,Long,"1,3,2",0.659261
3,Une femme,FEMME,De35a49ans1,De35a49ans2,Femme35ansEtPlus,PlusDe100000Habitants,UDA9,BUDA5,PROVINCE,ProvenceAlpesCoteDAzur,...,NaN,NaN,NaN,Moins de 50,Entre 1 et 49,NaN,NaN,Long,"1,2,3",1.165641
4,Un homme,HOMME,De50a64ans1,PlusDe49ans,Homme35ansEtPlus,MoinsDe100000Habitants,UDA8,BUDA5,PROVINCE,AuvergneRhoneAlpes,...,0,0,0,Moins de 50,0,NaN,Moins de 20,Long,"2,1,3",1.819044

In [25]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Columns: 261 entries, SEXE to poids
dtypes: float64(28), object(233)
memory usage: 4.4+ MB

In [26]:
df.columns.tolist() # nom de toutes les colonnes

['SEXE',
 'QSEXE',
 'RAGE2',
 'RAGE3',
 'XRAGE',
 'AGGLOIFOP2',
 'REG',
 'REG2',
 'REG3',
 'REG13',
 'REG13C',
 'PI4',
 'STATUT',
 'PCF4',
 'FOYER',
 'ENF',
 'RS1',
 'QRS1',
 'Q1_1',
 'Q1_2',
 'Q1_3',
 'Q1_4',
 'Q1_5',
 'Q1_6',
 'Q1_7',
 'Q1_8',
 'Q1_9',
 'Q1_10',
 'Q1_11',
 'Q2_r1',
 'Q2_r2',
 'Q2_r3',
 'Q2_r4',
 'Q2_r5',
 'Q2_r6',
 'Q2_r7',
 'Q2_r8',
 'Q2_r9',
 'Q2_r10',
 'Q2_r11',
 'Q3',
 'Q4',
 'Q5_1',
 'Q5_2',
 'Q5_3',
 'Q5_4',
 'Q5_5',
 'Q5_6',
 'Q5_7',
 'Q5_8',
 'Q5_9',
 'Q5_10',
 'Q5_11',
 'Q5_12',
 'Q5_13',
 'Q6_r1',
 'Q6_r2',
 'Q6_r3',
 'Q6_r4',
 'Q6_r5',
 'Q6_r6',
 'Q6_r7',
 'Q7',
 'Q7bis',
 'Q8_1',
 'Q8_2',
 'Q8_3',
 'Q8_4',
 'Q8_5',
 'Q8_6',
 'Q16_1',
 'Q16_2',
 'Q16_3',
 'Q16_4',
 'Q16_5',
 'Q16_6',
 'Q16_7',
 'Q16_8',
 'Q16_9',
 'Q16_10',
 'Q16_11',
 'Q16_12',
 'Q17',
 'Q18_1',
 'Q18_2',
 'Q18_3',
 'Q18_4',
 'Q18_5',
 'Q18_6',
 'Q18_7',
 'Q18_8',
 'Q18_9',
 'Q19_r1',
 'Q19_r2',
 'Q20_r1',
 'Q20_r2',
 'Q20_r3',
 'Q20_r4',
 'Q20_r5',
 'Q21_r1',
 'Q21_r2',
 'Q21_r3',
 'Q21_r4',
 'ALEA',
 'Q22ALEA1',
 'Q22ALEA2',
 'Q23_r1',
 'Q23_r2',
 'Q24_1',
 'Q24_2',
 'Q24_3',
 'Q24_4',
 'Q24_5',
 'Q24_6',
 'Q24_7',
 'Q24_8',
 'Q24_9',
 'Q24_10',
 'Q25_1',
 'Q25_2',
 'Q25_3',
 'Q25_4',
 'Q25_5',
 'Q25_6',
 'Q25_7',
 'Q25_8',
 'Q25_9',
 'Q25_10',
 'Q26_1',
 'Q26_2',
 'Q26_3',
 'Q26_4',
 'Q26_5',
 'Q27',
 'Q28',
 'Q29',
 'Q30_1',
 'Q30_2',
 'Q30_3',
 'Q31_r1',
 'Q31_r2',
 'Q31_r3',
 'Q31_r4',
 'Q31_r5',
 'Q31_r6',
 'Q31_r7',
 'Q31_r8',
 'Q31_r9',
 'Q32_1',
 'Q32_2',
 'Q32_3',
 'Q32_4',
 'Q32_5',
 'Q33_1',
 'Q33_2',
 'Q33_3',
 'Q33_4',
 'Q33_5',
 'Q34_r1',
 'Q34_r2',
 'Q35',
 'Q36_1',
 'Q36_2',
 'Q36_3',
 'Q36_4',
 'Q36_5',
 'Q37ALEA1',
 'Q37ALEA2',
 'Q38_r1_c1',
 'Q38_r2_c1',
 'Q48_1',
 'Q48_2',
 'Q48_3',
 'Q48_4',
 'Q48_5',
 'Q48_6',
 'Q48_7',
 'Q48_8',
 'Q48_9',
 'Q48_10',
 'Q48_11',
 'Q49_1',
 'Q49_2',
 'Q49_3',
 'Q49_4',
 'Q49_5',
 'Q49_6',
 'Q49_7',
 'Q49_8',
 'Q49_9',
 'Q50_1',
 'Q50_2',
 'Q50_3',
 'Q50_4',
 'Q50_5',
 'Q50_6',
 'Q50_7',
 'Q50_8',
 'Q50_9',
 'Q50_10',
 'Q50_11',
 'Q50_12',
 'Q51',
 'Q52_1',
 'Q52_2',
 'Q52_3',
 'Q52_4',
 'Q53_r1_c1',
 'Q53_r2_c1',
 'Q53_r3_c1',
 'Q53_r4_c1',
 'Q53_r5_c1',
 'Q53_r6_c1',
 'Q53_r7_c1',
 'Q53_r8_c1',
 'Q53_r9_c1',
 'Q53_r10_c1',
 'Q54_r1_c1',
 'Q54_r2_c1',
 'Q54_r3_c1',
 'Q54_r4_c1',
 'Q54_r5_c1',
 'Q54_r6_c1',
 'Q54_r7_c1',
 'Q54_r8_c1',
 'Q54_r9_c1',
 'Q55_1',
 'Q55_2',
 'Q55_3',
 'Q55_4',
 'Q55_5',
 'Q55_6',
 'Q55_7',
 'Q55_8',
 'Q56_r1_c1',
 'Q56_r2_c1',
 'Q56_r3_c1',
 'Q56_r4_c1',
 'Q56_r5_c1',
 'Q56_r6_c1',
 'Q57',
 'Q58_1',
 'Q58_2',
 'Q58_3',
 'Q58_4',
 'Q58_5',
 'Q58_6',
 'Q58_7',
 'Q59',
 'Q60_1',
 'Q60_2',
 'Q60_3',
 'Q60_4',
 'Q60_5',
 'Q61_r1_c1',
 'Q61_r2_c1',
 'Q61_r3_c1',
 'Q61_r4_c1',
 'DISPQUAL',
 'sys_block_set_1',
 'poids']

In [27]:
df.describe()

,Q2_r10,Q2_r11,Q53_r1_c1,Q53_r2_c1,Q53_r3_c1,Q53_r4_c1,Q53_r5_c1,Q53_r6_c1,Q53_r7_c1,Q53_r8_c1,...,Q54_r7_c1,Q54_r8_c1,Q54_r9_c1,Q56_r1_c1,Q56_r2_c1,Q56_r3_c1,Q56_r4_c1,Q56_r5_c1,Q56_r6_c1,poids
count,0.0,0.0,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,...,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,2200.000000
mean,NaN,NaN,6.531219,5.960725,6.213494,6.671702,6.359013,6.315710,6.044814,4.804632,...,6.525176,6.667170,6.489426,4.942095,4.972810,4.806143,5.061934,4.923464,4.871601,1.000000
std,NaN,NaN,2.500233,2.502889,2.471753,2.511831,2.574142,2.560999,2.578248,2.757924,...,2.338727,2.300695,2.334742,2.956131,2.949494,2.960901,3.037248,2.976344,2.983604,0.346235
min,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.492612
25%,NaN,NaN,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,3.000000,...,5.000000,5.000000,5.000000,3.000000,3.000000,2.000000,3.000000,3.000000,3.000000,0.765411
50%,NaN,NaN,7.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,5.000000,...,7.000000,7.000000,7.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,0.903059
75%,NaN,NaN,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,...,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,1.118734
max,NaN,NaN,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,2.700000

In [28]:
df.isna().sum() # nombre de valeurs manquantes par colonne

SEXE                  0
QSEXE                 0
RAGE2                 0
RAGE3                 0
XRAGE                 0
                   ...
Q61_r3_c1          1812
Q61_r4_c1          1980
DISPQUAL              0
sys_block_set_1     214
poids                 0
Length: 261, dtype: int64

In [29]:
df.duplicated().sum() # nombre de lignes dupliquées

np.int64(6)

In [ ]:
df.info(verbose=True, show_counts=True) # ça nous force l'affichage complet parce que info tout seul ça affiche que les 100 first

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 261 columns):
 #    Column           Non-Null Count  Dtype
---   ------           --------------  -----
 0    SEXE             2200 non-null   object
 1    QSEXE            2200 non-null   object
 2    RAGE2            2200 non-null   object
 3    RAGE3            2200 non-null   object
 4    XRAGE            2200 non-null   object
 5    AGGLOIFOP2       2200 non-null   object
 6    REG              2200 non-null   object
 7    REG2             2200 non-null   object
 8    REG3             2200 non-null   object
 9    REG13            2200 non-null   object
 10   REG13C           2200 non-null   object
 11   PI4              2200 non-null   object
 12   STATUT           2200 non-null   object
 13   PCF4             2200 non-null   object
 14   FOYER            2200 non-null   object
 15   ENF              1801 non-null   object
 16   RS1              2200 non-null   object
 17   QRS1             2200 non-null   object
 18   Q1_1             2200 non-null   object
 19   Q1_2             2200 non-null   object
 20   Q1_3             2200 non-null   object
 21   Q1_4             2200 non-null   object
 22   Q1_5             2200 non-null   object
 23   Q1_6             2200 non-null   object
 24   Q1_7             2200 non-null   object
 25   Q1_8             2200 non-null   object
 26   Q1_9             2200 non-null   object
 27   Q1_10            2200 non-null   object
 28   Q1_11            2200 non-null   object
 29   Q2_r1            1171 non-null   object
 30   Q2_r2            1092 non-null   object
 31   Q2_r3            998 non-null    object
 32   Q2_r4            1017 non-null   object
 33   Q2_r5            798 non-null    object
 34   Q2_r6            527 non-null    object
 35   Q2_r7            559 non-null    object
 36   Q2_r8            835 non-null    object
 37   Q2_r9            429 non-null    object
 38   Q2_r10           0 non-null      float64
 39   Q2_r11           0 non-null      float64
 40   Q3               2200 non-null   object
 41   Q4               1096 non-null   object
 42   Q5_1             1986 non-null   object
 43   Q5_2             1986 non-null   object
 44   Q5_3             1986 non-null   object
 45   Q5_4             1986 non-null   object
 46   Q5_5             1986 non-null   object
 47   Q5_6             1986 non-null   object
 48   Q5_7             1986 non-null   object
 49   Q5_8             1986 non-null   object
 50   Q5_9             1986 non-null   object
 51   Q5_10            1986 non-null   object
 52   Q5_11            1986 non-null   object
 53   Q5_12            1986 non-null   object
 54   Q5_13            1986 non-null   object
 55   Q6_r1            1986 non-null   object
 56   Q6_r2            1986 non-null   object
 57   Q6_r3            1986 non-null   object
 58   Q6_r4            1986 non-null   object
 59   Q6_r5            1986 non-null   object
 60   Q6_r6            1986 non-null   object
 61   Q6_r7            1986 non-null   object
 62   Q7               1338 non-null   object
 63   Q7bis            1673 non-null   object
 64   Q8_1             1667 non-null   object
 65   Q8_2             1667 non-null   object
 66   Q8_3             1667 non-null   object
 67   Q8_4             1667 non-null   object
 68   Q8_5             976 non-null    object
 69   Q8_6             1667 non-null   object
 70   Q16_1            1986 non-null   object
 71   Q16_2            1986 non-null   object
 72   Q16_3            1986 non-null   object
 73   Q16_4            1986 non-null   object
 74   Q16_5            1986 non-null   object
 75   Q16_6            1986 non-null   object
 76   Q16_7            1986 non-null   object
 77   Q16_8            1986 non-null   object
 78   Q16_9            1986 non-null   object
 79   Q16_10           1986 non-null   object
 80   Q16_11           1986 non-null   object
 81   Q16_12           1986 non-null   object
 82   Q17              1497 non-null   object
 83   Q18_1            1986 non-null   object
 84   Q18_2            1986 non-null   object
 85   Q18_3            1986 non-null   object
 86   Q18_4            1986 non-null   object
 87   Q18_5            1986 non-null   object
 88   Q18_6            1986 non-null   object
 89   Q18_7            1986 non-null   object
 90   Q18_8            1986 non-null   object
 91   Q18_9            1986 non-null   object
 92   Q19_r1           1986 non-null   object
 93   Q19_r2           1986 non-null   object
 94   Q20_r1           1986 non-null   object
 95   Q20_r2           1986 non-null   object
 96   Q20_r3           1986 non-null   object
 97   Q20_r4           1986 non-null   object
 98   Q20_r5           1986 non-null   object
 99   Q21_r1           1986 non-null   object
 100  Q21_r2           1986 non-null   object
 101  Q21_r3           1986 non-null   object
 102  Q21_r4           1986 non-null   object
 103  ALEA             1986 non-null   object
 104  Q22ALEA1         1037 non-null   object
 105  Q22ALEA2         949 non-null    object
 106  Q23_r1           1667 non-null   object
 107  Q23_r2           1667 non-null   object
 108  Q24_1            742 non-null    object
 109  Q24_2            1106 non-null   object
 110  Q24_3            395 non-null    object
 111  Q24_4            1986 non-null   object
 112  Q24_5            1026 non-null   object
 113  Q24_6            1986 non-null   object
 114  Q24_7            1986 non-null   object
 115  Q24_8            1986 non-null   object
 116  Q24_9            1986 non-null   object
 117  Q24_10           1986 non-null   object
 118  Q25_1            271 non-null    object
 119  Q25_2            399 non-null    object
 120  Q25_3            197 non-null    object
 121  Q25_4            330 non-null    object
 122  Q25_5            255 non-null    object
 123  Q25_6            369 non-null    object
 124  Q25_7            240 non-null    object
 125  Q25_8            172 non-null    object
 126  Q25_9            477 non-null    object
 127  Q25_10           13 non-null     object
 128  Q26_1            742 non-null    object
 129  Q26_2            742 non-null    object
 130  Q26_3            742 non-null    object
 131  Q26_4            742 non-null    object
 132  Q26_5            742 non-null    object
 133  Q27              742 non-null    object
 134  Q28              1986 non-null   object
 135  Q29              1986 non-null   object
 136  Q30_1            1052 non-null   object
 137  Q30_2            1052 non-null   object
 138  Q30_3            1052 non-null   object
 139  Q31_r1           1986 non-null   object
 140  Q31_r2           1986 non-null   object
 141  Q31_r3           1667 non-null   object
 142  Q31_r4           1667 non-null   object
 143  Q31_r5           1667 non-null   object
 144  Q31_r6           1986 non-null   object
 145  Q31_r7           229 non-null    object
 146  Q31_r8           229 non-null    object
 147  Q31_r9           229 non-null    object
 148  Q32_1            395 non-null    object
 149  Q32_2            395 non-null    object
 150  Q32_3            395 non-null    object
 151  Q32_4            395 non-null    object
 152  Q32_5            395 non-null    object
 153  Q33_1            395 non-null    object
 154  Q33_2            395 non-null    object
 155  Q33_3            395 non-null    object
 156  Q33_4            395 non-null    object
 157  Q33_5            395 non-null    object
 158  Q34_r1           1106 non-null   object
 159  Q34_r2           1106 non-null   object
 160  Q35              1096 non-null   object
 161  Q36_1            1096 non-null   object
 162  Q36_2            1096 non-null   object
 163  Q36_3            1096 non-null   object
 164  Q36_4            1096 non-null   object
 165  Q36_5            1096 non-null   object
 166  Q37ALEA1         572 non-null    object
 167  Q37ALEA2         524 non-null    object
 168  Q38_r1_c1        1096 non-null   object
 169  Q38_r2_c1        1096 non-null   object
 170  Q48_1            1986 non-null   object
 171  Q48_2            1986 non-null   object
 172  Q48_3            1986 non-null   object
 173  Q48_4            1986 non-null   object
 174  Q48_5            1986 non-null   object
 175  Q48_6            1986 non-null   object
 176  Q48_7            1986 non-null   object
 177  Q48_8            1986 non-null   object
 178  Q48_9            1986 non-null   object
 179  Q48_10           1986 non-null   object
 180  Q48_11           1986 non-null   object
 181  Q49_1            1986 non-null   object
 182  Q49_2            1986 non-null   object
 183  Q49_3            1986 non-null   object
 184  Q49_4            1986 non-null   object
 185  Q49_5            1986 non-null   object
 186  Q49_6            1986 non-null   object
 187  Q49_7            1986 non-null   object
 188  Q49_8            1986 non-null   object
 189  Q49_9            1986 non-null   object
 190  Q50_1            388 non-null    object
 191  Q50_2            388 non-null    object
 192  Q50_3            388 non-null    object
 193  Q50_4            388 non-null    object
 194  Q50_5            388 non-null    object
 195  Q50_6            388 non-null    object
 196  Q50_7            388 non-null    object
 197  Q50_8            388 non-null    object
 198  Q50_9            388 non-null    object
 199  Q50_10           388 non-null    object
 200  Q50_11           388 non-null    object
 201  Q50_12           388 non-null    object
 202  Q51              1598 non-null   object
 203  Q52_1            1257 non-null   object
 204  Q52_2            1257 non-null   object
 205  Q52_3            255 non-null    object
 206  Q52_4            1257 non-null   object
 207  Q53_r1_c1        1986 non-null   float64
 208  Q53_r2_c1        1986 non-null   float64
 209  Q53_r3_c1        1986 non-null   float64
 210  Q53_r4_c1        1986 non-null   float64
 211  Q53_r5_c1        1986 non-null   float64
 212  Q53_r6_c1        1986 non-null   float64
 213  Q53_r7_c1        1986 non-null   float64
 214  Q53_r8_c1        1986 non-null   float64
 215  Q53_r9_c1        1986 non-null   float64
 216  Q53_r10_c1       1986 non-null   float64
 217  Q54_r1_c1        1986 non-null   float64
 218  Q54_r2_c1        1986 non-null   float64
 219  Q54_r3_c1        1986 non-null   float64
 220  Q54_r4_c1        1986 non-null   float64
 221  Q54_r5_c1        1986 non-null   float64
 222  Q54_r6_c1        1986 non-null   float64
 223  Q54_r7_c1        1986 non-null   float64
 224  Q54_r8_c1        1986 non-null   float64
 225  Q54_r9_c1        1986 non-null   float64
 226  Q55_1            180 non-null    object
 227  Q55_2            180 non-null    object
 228  Q55_3            180 non-null    object
 229  Q55_4            180 non-null    object
 230  Q55_5            180 non-null    object
 231  Q55_6            180 non-null    object
 232  Q55_7            180 non-null    object
 233  Q55_8            180 non-null    object
 234  Q56_r1_c1        1986 non-null   float64
 235  Q56_r2_c1        1986 non-null   float64
 236  Q56_r3_c1        1986 non-null   float64
 237  Q56_r4_c1        1986 non-null   float64
 238  Q56_r5_c1        1986 non-null   float64
 239  Q56_r6_c1        1986 non-null   float64
 240  Q57              1667 non-null   object
 241  Q58_1            1074 non-null   object
 242  Q58_2            1074 non-null   object
 243  Q58_3            1074 non-null   object
 244  Q58_4            1074 non-null   object
 245  Q58_5            1074 non-null   object
 246  Q58_6            1074 non-null   object
 247  Q58_7            1074 non-null   object
 248  Q59              989 non-null    object
 249  Q60_1            402 non-null    object
 250  Q60_2            402 non-null    object
 251  Q60_3            402 non-null    object
 252  Q60_4            402 non-null    object
 253  Q60_5            402 non-null    object
 254  Q61_r1_c1        1026 non-null   object
 255  Q61_r2_c1        1543 non-null   object
 256  Q61_r3_c1        388 non-null    object
 257  Q61_r4_c1        220 non-null    object
 258  DISPQUAL         2200 non-null   object
 259  sys_block_set_1  1986 non-null   object
 260  poids            2200 non-null   float64
dtypes: float64(28), object(233)
memory usage: 4.4+ MB

In [31]:
df.nunique().sort_values()

Q2_r10           0
Q2_r11           0
SEXE             2
REG3             2
AGGLOIFOP2       2
              ...
Q56_r2_c1       11
Q17             12
REG13C          12
REG13           12
poids         1197
Length: 261, dtype: int64

In [36]:
pd.set_option("display.max_rows", None)

In [ ]:
# colonnes vides et constantes à supp 
nb = df.nunique()
print("vides :", nb[nb==0].index.tolist())
print("Constantes :", nb[nb==1].index.tolist())

vides : ['Q2_r10', 'Q2_r11']
Constantes : []

In [45]:
df.iloc[0]

SEXE                                                       Une femme
QSEXE                                                          FEMME
RAGE2                                                      De65aPlus
RAGE3                                                    PlusDe49ans
XRAGE                                               Femme35ansEtPlus
AGGLOIFOP2                                    MoinsDe100000Habitants
REG                                                             UDA7
REG2                                                           BUDA4
REG3                                                        PROVINCE
REG13                                       LanguedicRoussillonMidiP
REG13C                                        LanguedicRoussillonMi1
PI4                                                         INACTIFS
STATUT                                         Vous êtes célibataire
PCF4                                                       INACTIFS1
FOYER                                                     1 personne
ENF                                                              NaN
RS1                                          Plusieurs fois par jour
QRS1                                            PlusieursFoisParJour
Q1_1                                                               0
Q1_2                                                               0
Q1_3                                                               0
Q1_4                                                               0
Q1_5                                                               0
Q1_6                                                               0
Q1_7                                                               0
Q1_8                                                               0
Q1_9                                                               0
Q1_10                                                              0
Q1_11                                          Aucun de ces produits
Q2_r1                                                            NaN
Q2_r2                                                            NaN
Q2_r3                                                            NaN
Q2_r4                                                            NaN
Q2_r5                                                            NaN
Q2_r6                                                            NaN
Q2_r7                                                            NaN
Q2_r8                                                            NaN
Q2_r9                                                            NaN
Q2_r10                                                           NaN
Q2_r11                                                           NaN
Q3                                                     Moins souvent
Q4                                                               NaN
Q5_1                                               Variété Française
Q5_2                                                               0
Q5_3                                                               0
Q5_4                                                               0
Q5_5                                                            Jazz
Q5_6                                                               0
Q5_7                                                               0
Q5_8                                                               0
Q5_9                                                               0
Q5_10                                                           Soul
Q5_11                                                              0
Q5_12                                                              0
Q5_13                                                              0
Q6_r1                                                         Jamais
Q6_r2                                                         Jamais
Q6_r3                                                  Moins souvent
Q6_r4                                                  Moins souvent
Q6_r5                                                         Jamais
Q6_r6                                                  Moins souvent
Q6_r7                                      Tous les jours ou presque
Q7                                                               NaN
Q7bis                                                            Non
Q8_1                                                             NaN
Q8_2                                                             NaN
Q8_3                                                             NaN
Q8_4                                                             NaN
Q8_5                                                             NaN
Q8_6                                                             NaN
Q16_1                                                              0
Q16_2                                                              0
Q16_3                                                              0
Q16_4                                                              0
Q16_5                                                              0
Q16_6                                                              0
Q16_7                                                              0
Q16_8                                                              0
Q16_9                                                   Un autoradio
Q16_10                            Un poste de radio / un radioréveil
Q16_11                                            Une platine Vinyle
Q16_12                                                             0
Q17                               Un poste de radio / un radioréveil
Q18_1                                                              0
Q18_2                              Sous la douche, en vous préparant
Q18_3                                                              0
Q18_4                                                              0
Q18_5                                                     En voiture
Q18_6                                                              0
Q18_7                                                              0
Q18_8              Lorsque vous vous rassemblez avec des amis, de...
Q18_9                                                              0
Q19_r1                                     Tous les jours ou presque
Q19_r2                                                 Moins souvent
Q20_r1                               Ça ne me correspond pas du tout
Q20_r2                                  Ça me correspond tout à fait
Q20_r3                               Ça ne me correspond pas du tout
Q20_r4                             Ça ne me correspond pas très bien
Q20_r5                               Ça ne me correspond pas du tout
Q21_r1                                          Pas du tout d’accord
Q21_r2                                               Plutôt d’accord
Q21_r3                                          Pas du tout d’accord
Q21_r4                                           Plutôt pas d’accord
ALEA                                                           Alea1
Q22ALEA1           J’écoute surtout des titres à la mode que beau...
Q22ALEA2                                                         NaN
Q23_r1                                                           NaN
Q23_r2                                                           NaN
Q24_1                                                            NaN
Q24_2                                                            NaN
Q24_3                                                            NaN
Q24_4                                                              0
Q24_5                                                            NaN
Q24_6                                                              0
Q24_7                                                              0
Q24_8                                                              0
Q24_9                                                              0
Q24_10                       Autres moyens de découverte, précisez :
Q25_1                                                            NaN
Q25_2                                                            NaN
Q25_3                                                            NaN
Q25_4                                                            NaN
Q25_5                                                            NaN
Q25_6                                                            NaN
Q25_7                                                            NaN
Q25_8                                                            NaN
Q25_9                                                            NaN
Q25_10                                                           NaN
Q26_1                                                            NaN
Q26_2                                                            NaN
Q26_3                                                            NaN
Q26_4                                                            NaN
Q26_5                                                            NaN
Q27                                                              NaN
Q28                                                           Jamais
Q29                                                           Jamais
Q30_1                                                            NaN
Q30_2                                                            NaN
Q30_3                                                            NaN
Q31_r1                                          Pas du tout d’accord
Q31_r2                                               Plutôt d’accord
Q31_r3                                                           NaN
Q31_r4                                                           NaN
Q31_r5                                                           NaN
Q31_r6                                           Plutôt pas d’accord
Q31_r7                                               Plutôt d’accord
Q31_r8                                           Plutôt pas d’accord
Q31_r9                                           Plutôt pas d’accord
Q32_1                                                            NaN
Q32_2                                                            NaN
Q32_3                                                            NaN
Q32_4                                                            NaN
Q32_5                                                            NaN
Q33_1                                                            NaN
Q33_2                                                            NaN
Q33_3                                                            NaN
Q33_4                                                            NaN
Q33_5                                                            NaN
Q34_r1                                                           NaN
Q34_r2                                                           NaN
Q35                                                              NaN
Q36_1                                                            NaN
Q36_2                                                            NaN
Q36_3                                                            NaN
Q36_4                                                            NaN
Q36_5                                                            NaN
Q37ALEA1                                                         NaN
Q37ALEA2                                                         NaN
Q38_r1_c1                                                        NaN
Q38_r2_c1                                                        NaN
Q48_1                                                              0
Q48_2                                                              0
Q48_3                                                              0
Q48_4                                                              0
Q48_5                                                              0
Q48_6                                                              0
Q48_7                                                              0
Q48_8                                                              0
Q48_9                                                              0
Q48_10                                                             0
Q48_11                                              Autres avantages
Q49_1                                                              0
Q49_2                                                              0
Q49_3                                                              0
Q49_4                                                              0
Q49_5                                                              0
Q49_6                                                              0
Q49_7                                                              0
Q49_8                                                              0
Q49_9                                           Autres inconvénients
Q50_1                                                            NaN
Q50_2                                                            NaN
Q50_3                                                            NaN
Q50_4                                                            NaN
Q50_5                                                            NaN
Q50_6                                                            NaN
Q50_7                                                            NaN
Q50_8                                                            NaN
Q50_9                                                            NaN
Q50_10                                                           NaN
Q50_11                                                           NaN
Q50_12                                                           NaN
Q51                                                 Certainement pas
Q52_1                 Je ne souhaite pas payer un abonnement mensuel
Q52_2              Je n’écoute pas suffisamment de musique pour p...
Q52_3                                                            NaN
Q52_4                                                              0
Q53_r1_c1                                                        6.0
Q53_r2_c1                                                        5.0
Q53_r3_c1                                                        5.0
Q53_r4_c1                                                        3.0
Q53_r5_c1                                                        5.0
Q53_r6_c1                                                        4.0
Q53_r7_c1                                                        6.0
Q53_r8_c1                                                        0.0
Q53_r9_c1                                                        4.0
Q53_r10_c1                                                       5.0
Q54_r1_c1                                                        5.0
Q54_r2_c1                                                        5.0
Q54_r3_c1                                                        5.0
Q54_r4_c1                                                        5.0
Q54_r5_c1                                                        5.0
Q54_r6_c1                                                        5.0
Q54_r7_c1                                                        5.0
Q54_r8_c1                                                        5.0
Q54_r9_c1                                                        5.0
Q55_1                                                            NaN
Q55_2                                                            NaN
Q55_3                                                            NaN
Q55_4                                                            NaN
Q55_5                                                            NaN
Q55_6                                                            NaN
Q55_7                                                            NaN
Q55_8                                                            NaN
Q56_r1_c1                                                        0.0
Q56_r2_c1                                                        0.0
Q56_r3_c1                                                        0.0
Q56_r4_c1                                                        0.0
Q56_r5_c1                                                        0.0
Q56_r6_c1                                                        0.0
Q57                                                              NaN
Q58_1                                                            NaN
Q58_2                                                            NaN
Q58_3                                                            NaN
Q58_4                                                            NaN
Q58_5                                                            NaN
Q58_6                                                            NaN
Q58_7                                                            NaN
Q59                                                              NaN
Q60_1                                                            NaN
Q60_2                                                            NaN
Q60_3                                                            NaN
Q60_4                                                            NaN
Q60_5                                                            NaN
Q61_r1_c1                                                        NaN
Q61_r2_c1                                              Entre 1 et 49
Q61_r3_c1                                                        NaN
Q61_r4_c1                                                        NaN
DISPQUAL                                                        Long
sys_block_set_1                                                2,3,1
poids                                                       1.006791
Name: 0, dtype: object

In [ ]:
print(df["REG13"].value_counts(dropna=False))
print(df["REG13C"].value_counts(dropna=False))
pd.crosstab(df["REG13"], df["REG13C"])
# une valeur similaire par ligne donc on peut supprimer REG13C car c'est des colonnes identiques

REG13
IleDeFrance1                441
AuvergneRhoneAlpes          271
AlsaceChampagneArdenneLo    220
AquitaineLimousinPoitouC    210
NordPasDeCalaisPicardie     205
LanguedicRoussillonMidiP    178
ProvenceAlpesCoteDAzur      143
PaysDeLaLoire1              139
Bretagne1                   111
Normandie                   102
BourgogneFrancheComte        95
CentreValDeLoire             85
Name: count, dtype: int64
REG13C
IleDeFrance2              441
AuvergneRhoneAlpes1       271
AlsaceChampagneArdenn1    220
AquitaineLimousinPoit1    210
NordPasDeCalaisPicard1    205
LanguedicRoussillonMi1    178
PACACorse                 143
PaysDeLaLoire2            139
Bretagne2                 111
Normandie1                102
BourgogneFrancheComte1     95
CentreValDeLoire1          85
Name: count, dtype: int64

REG13C,AlsaceChampagneArdenn1,AquitaineLimousinPoit1,AuvergneRhoneAlpes1,BourgogneFrancheComte1,Bretagne2,CentreValDeLoire1,IleDeFrance2,LanguedicRoussillonMi1,NordPasDeCalaisPicard1,Normandie1,PACACorse,PaysDeLaLoire2
REG13,,,,,,,,,,,,
AlsaceChampagneArdenneLo,220,0,0,0,0,0,0,0,0,0,0,0
AquitaineLimousinPoitouC,0,210,0,0,0,0,0,0,0,0,0,0
AuvergneRhoneAlpes,0,0,271,0,0,0,0,0,0,0,0,0
BourgogneFrancheComte,0,0,0,95,0,0,0,0,0,0,0,0
Bretagne1,0,0,0,0,111,0,0,0,0,0,0,0
CentreValDeLoire,0,0,0,0,0,85,0,0,0,0,0,0
IleDeFrance1,0,0,0,0,0,0,441,0,0,0,0,0
LanguedicRoussillonMidiP,0,0,0,0,0,0,0,178,0,0,0,0
NordPasDeCalaisPicardie,0,0,0,0,0,0,0,0,205,0,0,0
Normandie,0,0,0,0,0,0,0,0,0,102,0,0
PaysDeLaLoire1,0,0,0,0,0,0,0,0,0,0,0,139
ProvenceAlpesCoteDAzur,0,0,0,0,0,0,0,0,0,0,143,0

In [ ]:
df["REG"].unique()

array(['UDA7', 'UDA6', 'UDA2', 'UDA9', 'UDA8', 'UDA3', 'UDA5', 'UDA1',
       'UDA4'], dtype=object)

In [47]:
df["REG2"].unique()

array(['BUDA4', 'BUDA3', 'BUDA2', 'BUDA5', 'BUDA1'], dtype=object)

In [ ]:
df["REG3"].unique() # localisation

array(['PROVINCE', 'RegionIleDeFrance'], dtype=object)

In [ ]:
df["AGGLOIFOP2"].unique() # proportion de la pop ds un lieu

array(['MoinsDe100000Habitants', 'PlusDe100000Habitants'], dtype=object)

In [50]:
pd.crosstab(df["REG13"], df["REG"])

REG                       UDA1  UDA2  UDA3  UDA4  UDA5  UDA6  UDA7  UDA8  UDA9
REG13
AlsaceChampagneArdenneLo     0     0   162    58     0     0     0     0     0
AquitaineLimousinPoitouC     0     0     0     0     0    42   168     0     0
AuvergneRhoneAlpes           0     0     0     0     0     0     0   271     0
BourgogneFrancheComte        0     0    37    58     0     0     0     0     0
Bretagne1                    0     0     0     0     0   111     0     0     0
CentreValDeLoire             0     0     0     0    85     0     0     0     0
IleDeFrance1               441     0     0     0     0     0     0     0     0
LanguedicRoussillonMidiP     0     0     0     0     0     0    98     0    80
NordPasDeCalaisPicardie      0   138     0    67     0     0     0     0     0
Normandie                    0     0     0     0   102     0     0     0     0
PaysDeLaLoire1               0     0     0     0     0   139     0     0     0
ProvenceAlpesCoteDAzur       0     0     0     0     0     0     0     0   143