In [ ]:
import pandas as pd
# filepath = '/Users/marzin/Documents/Ecole/Télécom/Kit Data Science/Projet musique git hub/data-science-project/documentation/hadopi-2020-musique-data.ods'
print("Dimensions des données brutes :", df.shape)

(2200, 261)

## Personnes identiques
#### Vérifier si des plusieurs personnes ont exactement les mêmes caractéristiques et les mêmes goûts musicaux
==> Personnes identiques et lesquelles

In [58]:
# lignes concernées (premières apparitions comprises)
print("Lignes concernées :", df.duplicated(keep=False).sum())

# Lignes à supprimer (premières apparitions non comprises)
print("Doublons à supprimer :", df.duplicated().sum())
display(df[df.duplicated(keep=False)])
# On comprend qu'il y a 6 paires de doublons

Lignes concernées : 12
Doublons à supprimer : 6

,SEXE,QSEXE,RAGE2,RAGE3,XRAGE,AGGLOIFOP2,REG,REG2,REG3,REG13,...,Q60_3,Q60_4,Q60_5,Q61_r1_c1,Q61_r2_c1,Q61_r3_c1,Q61_r4_c1,DISPQUAL,sys_block_set_1,poids
216,Un homme,HOMME,De65aPlus,PlusDe49ans,Homme35ansEtPlus,MoinsDe100000Habitants,UDA8,BUDA5,PROVINCE,AuvergneRhoneAlpes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Court,NaN,0.736057
394,Un homme,HOMME,De65aPlus,PlusDe49ans,Homme35ansEtPlus,PlusDe100000Habitants,UDA8,BUDA5,PROVINCE,AuvergneRhoneAlpes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Court,NaN,0.765518
572,Un homme,HOMME,De65aPlus,PlusDe49ans,Homme35ansEtPlus,MoinsDe100000Habitants,UDA6,BUDA3,PROVINCE,Bretagne1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Court,NaN,0.732905
680,Un homme,HOMME,De65aPlus,PlusDe49ans,Homme35ansEtPlus,MoinsDe100000Habitants,UDA8,BUDA5,PROVINCE,AuvergneRhoneAlpes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Court,NaN,0.736057
710,Un homme,HOMME,De65aPlus,PlusDe49ans,Homme35ansEtPlus,MoinsDe100000Habitants,UDA8,BUDA5,PROVINCE,AuvergneRhoneAlpes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Court,NaN,0.736057
712,Un homme,HOMME,De65aPlus,PlusDe49ans,Homme35ansEtPlus,PlusDe100000Habitants,UDA8,BUDA5,PROVINCE,AuvergneRhoneAlpes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Court,NaN,0.765518
1044,Un homme,HOMME,De65aPlus,PlusDe49ans,Homme35ansEtPlus,MoinsDe100000Habitants,UDA8,BUDA5,PROVINCE,AuvergneRhoneAlpes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Court,NaN,0.736057
1059,Une femme,FEMME,De65aPlus,PlusDe49ans,Femme35ansEtPlus,PlusDe100000Habitants,UDA9,BUDA5,PROVINCE,ProvenceAlpesCoteDAzur,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Court,NaN,1.804310
1063,Un homme,HOMME,De65aPlus,PlusDe49ans,Homme35ansEtPlus,MoinsDe100000Habitants,UDA6,BUDA3,PROVINCE,Bretagne1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Court,NaN,0.732905
1106,Une femme,FEMME,De65aPlus,PlusDe49ans,Femme35ansEtPlus,PlusDe100000Habitants,UDA9,BUDA5,PROVINCE,ProvenceAlpesCoteDAzur,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Court,NaN,1.804310
2002,Un homme,HOMME,De35a49ans1,De35a49ans2,Homme35ansEtPlus,PlusDe100000Habitants,UDA1,BUDA1,RegionIleDeFrance,IleDeFrance1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Court,NaN,0.882059
2014,Un homme,HOMME,De35a49ans1,De35a49ans2,Homme35ansEtPlus,PlusDe100000Habitants,UDA1,BUDA1,RegionIleDeFrance,IleDeFrance1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Court,NaN,0.882059

#### Suppression des doublons exact (sur les 261 colonnes)

In [61]:
df = df.drop_duplicates().copy()
print("Doublons restants :", df.duplicated().sum())
print("Dimension :", df.shape)

Doublons restants : 0
Dimension : (2194, 261)

## Réponses styles musicaux : cochés partout ou 0 réponses
#### Personnes qui ont sélectionné tous les style ou aucun style

#### Personnes qui ont cochés tous les styles de musique
Une personne. Cette personne écoute de la musique plusieurs fois par jours ==> voir si suppression de cette ligne 
(Q3 = De manière générale, à quelle fréquence consommez-vous de la musique ou des vidéo clips , quel que soit le support ou le moyen de consommation ?)

In [ ]:
colonnes_genres = dataset.columns.drop("region")

tous_styles = dataset[
    dataset[colonnes_genres].sum(axis=1) == 13
]

print("Personnes ayant sélectionné les 13 styles :", len(tous_styles))
display(tous_styles)

,Q5_1,Q5_2,Q5_3,Q5_4,Q5_5,Q5_6,Q5_7,Q5_8,Q5_9,Q5_10,Q5_11,Q5_12,Q5_13
45,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

#### Personnes qui n'ont rien coché

In [ ]:
aucun_style = dataset[
    (dataset[colonnes_genres].sum(axis=1) == 0) &
    (dataset[colonnes_genres].notnull().all(axis=1))
]

Empty DataFrame
Columns: [Q5_1, Q5_2, Q5_3, Q5_4, Q5_5, Q5_6, Q5_7, Q5_8, Q5_9, Q5_10, Q5_11, Q5_12, Q5_13]
Index: []