In [17]:
import pandas as pd
filepath = '/Users/marzin/Documents/Ecole/Télécom/Kit Data Science/Projet musique git hub/data-science-project/documentation/hadopi-2020-musique-data.ods'
df = pd.read_excel(filepath, engine="odf", na_values=["#NUL!"])
df.shape

(2200, 261)

## Personnes identiques
#### Vérifier si des plusieurs personnes ont exactement les mêmes caractéristiques et les mêmes goûts musicaux
==> Personnes identiques et lesquelles

In [18]:
# lignes concernées (premières apparitions comprises)
print("Personnes identiques :", df.duplicated(keep=False).sum())

# Lignes à supprimer (premières apparitions non comprises)
print("Doublons à supprimer :", df.duplicated().sum())
df[df.duplicated()]

# On comprend qu'il y a 6 paires de doublons

Personnes identiques : 12
Doublons à supprimer : 6

,SEXE,QSEXE,RAGE2,RAGE3,XRAGE,AGGLOIFOP2,REG,REG2,REG3,REG13,...,Q60_3,Q60_4,Q60_5,Q61_r1_c1,Q61_r2_c1,Q61_r3_c1,Q61_r4_c1,DISPQUAL,sys_block_set_1,poids
710,Un homme,HOMME,De65aPlus,PlusDe49ans,Homme35ansEtPlus,MoinsDe100000Habitants,UDA8,BUDA5,PROVINCE,AuvergneRhoneAlpes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Court,NaN,0.736057
712,Un homme,HOMME,De65aPlus,PlusDe49ans,Homme35ansEtPlus,PlusDe100000Habitants,UDA8,BUDA5,PROVINCE,AuvergneRhoneAlpes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Court,NaN,0.765518
1044,Un homme,HOMME,De65aPlus,PlusDe49ans,Homme35ansEtPlus,MoinsDe100000Habitants,UDA8,BUDA5,PROVINCE,AuvergneRhoneAlpes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Court,NaN,0.736057
1063,Un homme,HOMME,De65aPlus,PlusDe49ans,Homme35ansEtPlus,MoinsDe100000Habitants,UDA6,BUDA3,PROVINCE,Bretagne1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Court,NaN,0.732905
1106,Une femme,FEMME,De65aPlus,PlusDe49ans,Femme35ansEtPlus,PlusDe100000Habitants,UDA9,BUDA5,PROVINCE,ProvenceAlpesCoteDAzur,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Court,NaN,1.804310
2014,Un homme,HOMME,De35a49ans1,De35a49ans2,Homme35ansEtPlus,PlusDe100000Habitants,UDA1,BUDA1,RegionIleDeFrance,IleDeFrance1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Court,NaN,0.882059

#### Supprimer les personnes identiques

In [19]:
sans_doublons = df.drop_duplicates().copy()
print(sans_doublons.duplicated().sum())
print(sans_doublons.shape)

0
(2194, 261)

## Réponses styles musicaux : cochés partout ou 0 réponses
#### Personnes qui ont baclés leurs réponses

In [ ]:
# transformation des réponses en 0 et 1 
dataset_code = sans_doublons.copy()
style = [f"Q5_{i}" for i in range(1, 14)]

codage = {
    '0': 0,
    '1': 1,
    'Variété Française': 1,
    'Pop / Rock': 1,
    'Rap / Hip-Hop': 1,
    'Classique': 1,
    'Jazz': 1,
    'Dance': 1,
    'Electronique': 1,
    'Métal': 1,
    'R&B': 1,
    'Soul': 1,
    'Reggae': 1,
    'Musiques du monde': 1,
    'Autres genres': 1
}

for colonne in style:
    reponses = dataset_code[colonne].astype("string").str.strip()
    dataset_code[colonne] = reponses.map(codage)

dataset_code[style].head()

,Q5_1,Q5_2,Q5_3,Q5_4,Q5_5,Q5_6,Q5_7,Q5_8,Q5_9,Q5_10,Q5_11,Q5_12,Q5_13
0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

#### Personnes qui ont cochés tous les styles de musique
Une personne. Cette personne écoute de la musique plusieurs fois par jours ==> voir si suppression de cette ligne 
(Q3 = De manière générale, à quelle fréquence consommez-vous de la musique ou des vidéo clips , quel que soit le support ou le moyen de consommation ?)

In [51]:
dataset_code[style][dataset_code[style].sum(axis=1) > 12]

,Q5_1,Q5_2,Q5_3,Q5_4,Q5_5,Q5_6,Q5_7,Q5_8,Q5_9,Q5_10,Q5_11,Q5_12,Q5_13
45,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

#### Personnes qui n'ont rien coché

In [56]:
dataset_code[style][(dataset_code[style].sum(axis=1) == 0) & (dataset_code[style].notna().all(axis=1))]

Empty DataFrame
Columns: [Q5_1, Q5_2, Q5_3, Q5_4, Q5_5, Q5_6, Q5_7, Q5_8, Q5_9, Q5_10, Q5_11, Q5_12, Q5_13]
Index: []